// GENERATED by ofis-qa · web/default · template_version 0.2.0 · 2026-07-19T16:59:24+00:00
// Bu dosya ofis-qa'ya AİTTİR — `ofis-qa upgrade` değiştirebilir. Testlerin e2e/ altında (SANA ait).
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  timeout: 30_000,
  expect: { timeout: 5_000 },
  retries: process.env.CI ? 2 : 0,
  forbidOnly: !!process.env.CI,
  reporter: [['line'], ['html', { open: 'never' }], ['allure-playwright']],
  use: {
    baseURL: process.env.QA_BASE_URL ?? 'http://localhost:8000',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'retain-on-failure',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
});
