# GENERATED by ofis-qa · backend_integration/python · template_version 0.2.0 · AurasVision — Görüntü Analitiği Platformu
# Gerçek PostgreSQL'e karşı entegrasyon. testcontainers 4.8.0 + pytest. Mock DB YASAK.
import pytest
from testcontainers.postgres import PostgresContainer


@pytest.fixture(scope="session")
def pg():
    with PostgresContainer("postgres:16-alpine") as container:   # pinli imaj
        yield container


def test_gercek_postgres_ayaga_kalkiyor(pg):
    url = pg.get_connection_url()
    assert "postgresql" in url
    # uygulamayı url ile başlat (FastAPI TestClient vs), gerçek endpoint/sorgu doğrula
