// GENERATED by ofis-qa · örnek smoke · AurasVision — Görüntü Analitiği Platformu
// Başlangıç örneği — kendi testlerini bu dizine ekle (onlar SANA ait, ofis-qa dokunmaz).
import { test, expect } from '@playwright/test';

test('uygulama açılıyor (smoke)', async ({ page }) => {
  const res = await page.goto('/');
  expect(res, 'ana sayfa yanıt vermeli').toBeTruthy();
  expect(res!.status(), 'HTTP < 400 olmalı').toBeLessThan(400);
  await expect(page).toHaveTitle(/.+/);
});

test.skip('login akışı — TODO: gerçek selektörlerle doldur', async ({ page }) => {
  await page.goto('/login');
  // await page.getByLabel('E-posta').fill(process.env.QA_USER!);
  // await page.getByRole('button', { name: 'Giriş' }).click();
  // await expect(page).toHaveURL(/dashboard/);
});
